// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCau4Nw39P66myrg8FwQtvID4AxER3KRg4',
    appId: '1:234341376593:web:7627c43f322c1c00aa4e70',
    messagingSenderId: '234341376593',
    projectId: 'utm-courtify',
    authDomain: 'utm-courtify.firebaseapp.com',
    storageBucket: 'utm-courtify.firebasestorage.app',
    measurementId: 'G-V6CRWD65NL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyRQaHobREU55drrYmx3E6Hxp9PI42y3M',
    appId: '1:234341376593:android:5c2055db5ba9977eaa4e70',
    messagingSenderId: '234341376593',
    projectId: 'utm-courtify',
    storageBucket: 'utm-courtify.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDThYRA8qXGfjO_STHFTUD7C-ifuxAfbPU',
    appId: '1:234341376593:ios:8cb2f08cfa5bdc25aa4e70',
    messagingSenderId: '234341376593',
    projectId: 'utm-courtify',
    storageBucket: 'utm-courtify.firebasestorage.app',
    iosBundleId: 'com.example.utmCourtify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDThYRA8qXGfjO_STHFTUD7C-ifuxAfbPU',
    appId: '1:234341376593:ios:8cb2f08cfa5bdc25aa4e70',
    messagingSenderId: '234341376593',
    projectId: 'utm-courtify',
    storageBucket: 'utm-courtify.firebasestorage.app',
    iosBundleId: 'com.example.utmCourtify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCau4Nw39P66myrg8FwQtvID4AxER3KRg4',
    appId: '1:234341376593:web:848925c095e7b835aa4e70',
    messagingSenderId: '234341376593',
    projectId: 'utm-courtify',
    authDomain: 'utm-courtify.firebaseapp.com',
    storageBucket: 'utm-courtify.firebasestorage.app',
    measurementId: 'G-3C0VL8QLPR',
  );
}
